# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 03:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='trueorfalseanswer',
            name='answers',
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='answer_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(4)]), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textanswer',
            name='answer_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=[], size=None),
            preserve_default=False,
        ),
    ]
