# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import studytime.questions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20170510_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='flags',
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='answer_array',
            field=studytime.questions.fields.ChoiceArrayField(base_field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1), default=['a'], size=None),
        ),
    ]
