# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 16:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20170510_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='answer_singular',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trueorfalseanswer',
            name='answer_singular',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='answer_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1), default=['a'], size=None),
        ),
    ]
