# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='trueorfalsequestion',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.TextQuiz'),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
