# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 21:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=250)),
                ('reprompt', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='question',
            old_name='prompt',
            new_name='prompt_text',
        ),
    ]
