# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170416_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueOrFalseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=250)),
                ('reprompt_text', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='multiplechoicequestion',
            old_name='reprompt',
            new_name='reprompt_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='reprompt',
            new_name='reprompt_text',
        ),
    ]
