# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_multiplechoiceanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.MultipleChoiceQuestion'),
        ),
    ]
