# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20170416_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueOrFalseAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_bool', models.BooleanField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.TrueOrFalseQuestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
