# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_trueorfalseanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='TextAnswer',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='TextQuestion',
        ),
    ]
