# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0007_auto_20170507_2109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(default=0)),
                ('incorrect', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='quiz.MultipleChoiceQuiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
