# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicescore',
            name='quiz',
        ),
        migrations.AddField(
            model_name='multiplechoicescore',
            name='question',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='questions.MultipleChoiceQuestion'),
            preserve_default=False,
        ),
    ]
