# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_textscore_trueorfalsescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicescore',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='questions.MultipleChoiceQuestion'),
        ),
        migrations.AlterField(
            model_name='textscore',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='questions.TextQuestion'),
        ),
        migrations.AlterField(
            model_name='trueorfalsescore',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='questions.TrueOrFalseQuestion'),
        ),
    ]
