# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 19:46
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='1', max_length=100, no_check_for_status=True),
        ),
    ]
